export const SET_ALL_SELLER = "SET_ALL_SELLER";
export const ADD_SELLER = "ADD_SELLER";
export const UPDATE_SELLER = "UPDATE_SELLER";
export const DELETE_SELLER = "DELETE_SELLER";
export const SET_SELLER_ACTION_MESSAGE = "SET_SELLER_ACTION_MESSAGE";
